In [1]:
import pandas as pd
    #Create Series
planets = pd.Series(["Mercury","Venus","Earth","Mars","Jupiter","Saturn","Uranus","Neptune","Pluto"])
moons = pd.Series([0,0,1,2,95,146,27,14,5])
planet_diameter_Km = pd.Series([4890,12104,12756,6794,142984,120536.51118,2378.6])
planet_type = pd.Series(["Terrestrial","Terrestrial","Terrestrial","Terrestrial","Gas","Gas",
                         "Ice","Ice","Dwarf"])
dist_frm_sun = pd.Series([58,108,150,227.9,778,1400,2900,4500,5900])
    #Create Dataframe
Planets_df = pd.DataFrame({"Planets":planets,"Moons":moons,"Planet Diameter(Km)":planet_diameter_Km,
                           "Planet Type":planet_type,"Dist frm sun":dist_frm_sun})
Planets_df

   Planets  Moons  Planet Diameter(Km)  Planet Type  Dist frm sun
0  Mercury      0           4890.00000  Terrestrial          58.0
1    Venus      0          12104.00000  Terrestrial         108.0
2    Earth      1          12756.00000  Terrestrial         150.0
3     Mars      2           6794.00000  Terrestrial         227.9
4  Jupiter     95         142984.00000          Gas         778.0
5   Saturn    146         120536.51118          Gas        1400.0
6   Uranus     27           2378.60000          Ice        2900.0
7  Neptune     14                  NaN          Ice        4500.0
8    Pluto      5                  NaN        Dwarf        5900.0

In [2]:
    #output by coordinate via column name and index(single)
Planets_df.loc[3,"Planet Type"]

'Terrestrial'

In [4]:
    #output by coordinate grid range (multiple cells)
Planets_df.loc[2:6,"Moons":"Dist frm sun"]

   Moons  Planet Diameter(Km)  Planet Type  Dist frm sun
2      1          12756.00000  Terrestrial         150.0
3      2           6794.00000  Terrestrial         227.9
4     95         142984.00000          Gas         778.0
5    146         120536.51118          Gas        1400.0
6     27           2378.60000          Ice        2900.0

In [5]:
    #output entire row
Planets_df.loc[2]

Planets                      Earth
Moons                            1
Planet Diameter(Km)        12756.0
Planet Type            Terrestrial
Dist frm sun                 150.0
Name: 2, dtype: object

In [8]:
    #output entire column
Planets_df.loc[:,"Planet Type"]

0    Terrestrial
1    Terrestrial
2    Terrestrial
3    Terrestrial
4            Gas
5            Gas
6            Ice
7            Ice
8          Dwarf
Name: Planet Type, dtype: object

In [9]:
    #output by coordinate via index (single cell)
Planets_df.iloc[1,3]

'Terrestrial'

In [10]:
    #output by coordinate via index (multi cell)
Planets_df.iloc[2:7,1:3]

   Moons  Planet Diameter(Km)
2      1          12756.00000
3      2           6794.00000
4     95         142984.00000
5    146         120536.51118
6     27           2378.60000

In [11]:
    #output entire row
Planets_df.iloc[4]

Planets                 Jupiter
Moons                        95
Planet Diameter(Km)    142984.0
Planet Type                 Gas
Dist frm sun              778.0
Name: 4, dtype: object

In [12]:
    #output entire column
Planets_df.iloc[:,4]

0      58.0
1     108.0
2     150.0
3     227.9
4     778.0
5    1400.0
6    2900.0
7    4500.0
8    5900.0
Name: Dist frm sun, dtype: float64

In [1]:
x = "hello"
print(x)

hello